version: "3.7"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=qdoc
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password

  firebase:
    image: firebase-auth:latest
    build:
      context: ./firebase
    volumes:
      - "./firebase:/home/node"
    ports:
      - "9098:9098"