name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [ "tests" ]
    types: [ completed ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      STAGING_GCP_PROJECT_ID: ${{ secrets.STAGING_GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker login
        run: echo $GCP_SERVICE_ACCOUNT_JSON | docker login -u _json_key --password-stdin https://asia.gcr.io
      - name: Docker build
        run: docker build . -t https://asia.gcr.io/$STAGING_GCP_PROJECT_ID/qdoc
      - name: Push to GCR
        run: docker push