name: build

on:
  workflow_run:
    workflows: [ "tests" ]
    types: [ completed ]
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker login
        env:
          GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: echo $GCP_SERVICE_ACCOUNT_JSON | docker login -u _json_key --password-stdin https://asia.gcr.io