name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [ "tests" ]
    types: [ completed ]
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      STAGING_GCP_PROJECT_ID: ${{ secrets.STAGING_GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker login
        run: echo $GCP_SERVICE_ACCOUNT_JSON | docker login -u _json_key --password-stdin https://asia.gcr.io
      - name: Docker build
        run: docker build . -t qdoc
      - name: Docker tag latest
        run: docker tag qdoc asia.gcr.io/"$STAGING_GCP_PROJECT_ID"/qdoc:latest
      - name: Docker tag sha
        run: docker tag qdoc asia.gcr.io/"$STAGING_GCP_PROJECT_ID"/qdoc:"${GITHUB_SHA}"
      - name: Push to GCR with tag sha
        run: docker push asia.gcr.io/"$STAGING_GCP_PROJECT_ID"/qdoc:"${GITHUB_SHA}"
      - name: Push to GCR with latest
        run: docker push asia.gcr.io/"$STAGING_GCP_PROJECT_ID"/qdoc:latest