name: deploy-staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [ "build" ]
    types: [ completed ]
jobs:
  deploy-staging:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    container: docker://hashicorp/terraform:0.15.3
    env:
      TF_VAR_project_id: ${{ secrets.STAGING_GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      TF_VAR_db_user: ${{ secrets.STAGING_DB_USER }}
      TF_VAR_db_password: ${{ secrets.STAGING_DB_PASSWORD }}
      TF_VAR_db_host: ${{ secrets.STAGING_DB_HOST }}
      TF_VAR_db_database: ${{ secrets.STAGING_DB_DATABASE }}
      TF_VAR_gcp_auth_file: "terraform/creds/keys.json"
      TF_VAR_cloud_sql_instance_name: "qdoc-postgres-staging"
      SERVICE_ACCOUNT_KEY_FILE_PATH: "terraform/creds/keys.json"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install jq
        run: apk add jq
      - name: Copy Service Account to File
        run: echo $GCP_SERVICE_ACCOUNT_JSON | jq . > $SERVICE_ACCOUNT_KEY_FILE_PATH
      - name: List file at creds
        run: ls terraform/creds
      - name: Terraform Init
        run: terraform -chdir="terraform" init
      - name: Terraform Plan
        run: terraform -chdir="terraform" plan