name: deploy-staging

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_run:
    workflows: [ "build" ]
    types: [ completed ]
jobs:
  build:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      STAGING_GCP_PROJECT_ID: ${{ secrets.STAGING_GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      TF_VAR_db_user: ${{ secrets.STAGING_DB_USER }}
      TF_VAR_db_password: ${{ secrets.STAGING_DB_PASSWORD }}
      TF_VAR_db_host: ${{ secrets.STAGING_DB_HOST }}
      SERVICE_ACCOUNT_KEY_FILE_PATH: "./terraform/creds/keys.json"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install jq
        run: apt install jq
      - name: Copy service account json
        run: echo $GCP_SERVICE_ACCOUNT_JSON | jq . > $SERVICE_ACCOUNT_KEY_FILE_PATH
      - name: Terraform Init
        run: terraform -chdir="terraform" init
      - name: Terraform Plan
        run: terraform -chdir="terraform" plan