name: Staging CI

on:
  push:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest
    env:
      DB_PASSWORD: password
      DB_USERNAME: postgres
      DB_HOSTNAME: localhost
      DB_DATABASE: qdoc_ci
      NODE_ENV: ci
      FIREBASE_CONFIG: ${{ secrets.STAGING_FIREBASE_CONFIG }}
      FIREBASE_AUTH_EMULATOR_HOST: 'firebase:9098'
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{ env.DB_PASSWORD }}
          POSTGRES_USER: ${{ env.DB_USERNAME }}
          POSTGRES_DB: ${{ env.DB_DATABASE }}
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      firebase:
        image: weewey/firebase-auth-ci
        ports:
          - 9098:9098

    strategy:
      matrix:
        node-version: [ 15.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Run migrations on DB
        run: npm run db:setup
      - name: Run test
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: tests
    env:
      STAGING_GCP_PROJECT_ID: ${{ secrets.STAGING_GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Docker login
        run: echo $GCP_SERVICE_ACCOUNT_JSON | docker login -u _json_key --password-stdin https://asia.gcr.io
      - name: Docker build
        run: docker build . -t qdoc
      - name: Docker tag latest
        run: docker tag qdoc asia.gcr.io/"$STAGING_GCP_PROJECT_ID"/qdoc:latest
      - name: Docker tag sha
        run: docker tag qdoc asia.gcr.io/"$STAGING_GCP_PROJECT_ID"/qdoc:"${GITHUB_SHA}"
      - name: Push to GCR with tag sha
        run: docker push asia.gcr.io/"$STAGING_GCP_PROJECT_ID"/qdoc:"${GITHUB_SHA}"
      - name: Push to GCR with latest
        run: docker push asia.gcr.io/"$STAGING_GCP_PROJECT_ID"/qdoc:latest

  deploy-staging:
    runs-on: ubuntu-latest
    container: docker://hashicorp/terraform:0.15.3
    needs: [tests, build]
    env:
      TF_VAR_project_id: ${{ secrets.STAGING_GCP_PROJECT_ID }}
      GCP_SERVICE_ACCOUNT_JSON: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
      TF_VAR_db_user: ${{ secrets.STAGING_DB_USER }}
      TF_VAR_db_password: ${{ secrets.STAGING_DB_PASSWORD }}
      TF_VAR_db_host: ${{ secrets.STAGING_DB_HOST }}
      TF_VAR_db_database: ${{ secrets.STAGING_DB_DATABASE }}
      TF_VAR_gcp_auth_file: "./creds/keys.json"
      TF_VAR_cloud_sql_instance_name: ${{ secrets.STAGING_CLOUD_SQL_INSTANCE_NAME }}
      TF_VAR_docker_image_tag: ${{ github.sha }}
      SERVICE_ACCOUNT_KEY_FILE_PATH: "terraform/creds/keys.json"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install jq
        run: apk add jq
      - name: Copy Service Account to File
        run: echo $GCP_SERVICE_ACCOUNT_JSON | jq . > $SERVICE_ACCOUNT_KEY_FILE_PATH
      - name: List file at creds
        run: ls terraform/creds
      - name: Terraform Init
        run: terraform -chdir="terraform" init
      - name: Terraform Plan
        run: terraform -chdir="terraform" plan
      - name: Terraform Apply
        run: terraform -chdir="terraform" apply -auto-approve
